### ISSUE TITLE
Block

### ISSUE THREAD

**Issue by asi90sp** [WalletConnect/WalletConnectSwiftV2#1031]
1.pless block .shot out

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**
```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/1030
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1029
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/pull/991
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1016
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/329
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1025
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/998
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/pull/1027
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/pull/911
```

**Comment by asi90sp** [comment]
Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22
 - please ful item out and goin Block. Full item wallet .....

**Comment by asi90sp** [comment]
Ok

**Comment by asi90sp** [comment]
Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]
 - pless delet ip
