### ISSUE TITLE
Improve Inbox page

### ISSUE THREAD

**Issue by herrhaase** [WalletConnect/WalletConnectSwiftV2#1180]
```[tasklist]
### Tasks
- [ ] Add divider line under tab bar
- [ ] Add badge for new notifications
- [ ] Clear new notifications when viewed (see below)
- [ ] Remove blur background behind tab bar
- [ ] Proper subscribed button style
- [ ] Improve app cards on Discover
```

**Comment by herrhaase** [comment]
**Add divider line under tab bar**

<img width="730" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/707251/3210a2da-fca6-4aa1-9779-b7eddd6e4b6a">

**Comment by herrhaase** [comment]
**Clear new notifications when viewed**

As a user, I expect the new notification badge to disappear after I viewed the notifications, so I can see a clear difference whenever I have unseen notifications.

**Comment by herrhaase** [comment]
**Remove blur background behind tab bar – 100% white**

![IMG_1126](https://github.com/WalletConnect/WalletConnectSwiftV2/assets/707251/68845ba3-b274-4b79-89b1-1dd5006dea88)

**Comment by herrhaase** [comment]
**Proper subscribed button style**

<img width="773" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/707251/9262d123-8d80-4623-b22a-4c5fe052e7cf">

**Comment by herrhaase** [comment]
**Improve Dapp cards on Discover**

Design details [here](https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=2752%3A96639&mode=design&t=KXJ0vH3LTti0afI6-1)

- [ ] Check dapp-name font stylings (should be SF Pro Semibold)
- [ ] Check domain font stylings (should not be rounded)
- [ ] Add the verified badge for all official (WalletConnect) apps
- [ ] Add thin outline around avatar
- [ ] Add [placeholder avatar](https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=3432%3A65755&mode=design&t=KXJ0vH3LTti0afI6-1) for every app without uploaded avatar

**Comment by herrhaase** [comment]
**When subscribed, make app card tappable**

As a user I expect on the discover page to be able to tap on the card of an app I am subscribed to, and then get redirected to that app page – eg. when subsribed to "GM Dapp" tapping on the GM Dapp card on the Discover page, brings me to the GM Dapp page with all notifications.
