### ISSUE TITLE
Improve App page

### ISSUE THREAD

**Issue by herrhaase** [WalletConnect/WalletConnectSwiftV2#1181]
```[tasklist]
### Tasks
- [ ] Improve header
- [ ] Improve notification list
- [ ] Add sticky header when scrolled
- [ ] Change all default notification images to app icon
```

**Comment by herrhaase** [comment]
**Improve header**

<img width="535" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/707251/498412fc-3b3b-4f7c-a620-47352e076287">

- [ ] Add background gradient
- [ ] Check button style
- [ ] Add verification badge for official (WalletConnect) apps
- [ ] Update "Settings" icon with ...
- [ ] Update avatar with [this one](https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=3390%3A51470&mode=design&t=KXJ0vH3LTti0afI6-1)

**Comment by herrhaase** [comment]
**Improve notification list**

<img width="544" alt="Screenshot 2023-10-13 at 16 33 21" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/707251/3ab35392-6ec0-46b8-b80b-1b0632756a5a">

- [ ] Add design / support for "unread" notifications
- [ ] Improve "x ago" labels for brevity according to design ( "14minutes ago" -> "14m" / "2 days ago" -> "2d" etc.)
- [ ] Ensure there is only 1 separator line going across edge-to-edge

**Comment by herrhaase** [comment]
**Add mini-header when scrolled**

<img width="640" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/707251/1ca9f0dc-97b4-47d0-9bf9-cc1cfc08be60">

**Comment by herrhaase** [comment]
**Change all avatars to app icon**

Not sure why I didn't see this earlier (lol), but please change the img for each notification to the app icon as the default img. Projects are able to specify different images per notification category, but if no category or different img is specified, we always default to the app's avatar.

<img width="496" alt="image" src="https://github.com/WalletConnect/WalletConnectSwiftV2/assets/707251/04683309-7274-41a0-9225-dc2e52041bea">
