### ISSUE TITLE
Swift Auth Alpha

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/WalletConnectSwiftV2#417]
See https://github.com/WalletConnect/walletconnect-docs/issues/253 for scope and brief.

- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/396
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/395
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/394
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/380
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/379
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/377
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/376
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/375
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/374
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/367
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/416 
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/415
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/390
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/389
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/382
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/378
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/464
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/459
- [x] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/451
- [x] #476
- [ ] Bug and release testing
- [ ] tests with js and kotlin
