### ISSUE TITLE
Implement Auth package into showcase app

### ISSUE THREAD

**Issue by MisterVants** [WalletConnect/WalletConnectSwiftV2#439]
### Description
The goal of this integration is to be able to perform a full end-to-end authentication from the example apps.

The breakdown of this goal comprises of the following points:
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/454
- [ ] Display the Auth QR code from the Dapp
- [ ] Add a secondary scanner to the wallet to interact with Auth API*
- [ ] Create an Auth request prompt view in a similar fashion to Sign's proposal-approve flow
- [ ] Implement Dapp feedback for successful authentication

### Notes
The current URI schema is indistinguishable to both Auth and Sign APIs, thus it needs, for now, a separate QR code generator and scanner to do the routing to the correct API. This is an UX issue to be discussed with the whole team.
