### ISSUE TITLE
Pairing API

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/WalletConnectSwiftV2#524]
- [x] Pairing client interface 
- [x] Integrate pairing into Auth
- [x] Integrate pairing into Sign
- [x] Pairing related methods depreciation in SignClient
- [x] #525
- [x] Activate pairing from SignClient
- [x] Activate pairing from AuthClient
- [x] #528
- [x] #527
- [x] Update pairing expiry from sign and auth packages
- [x] #526
- [x] #529
- [x] #530
- [x] #537
- [x] Update Auth and Sign documentation for Pairing instance usage
- [x] Hide pair.instance methods(activate, updateExpiry etc.) with protocol
