### ISSUE TITLE
[Auth] Auth Beta

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/WalletConnectSwiftV2#539]
- [x] Domain binding
- [x] Support EIP-1271
- [x] Pairing API integration
- [x] EIP-1271 Signature Verifier
- [x] App EIP-191 response handler (should be extracted from AppRespondSubscriber)
- [x] App EIP-1271 response handler
- [x] Refactor message signer to support CacaoSignature eip191 and eip1271
- [x] eip1271 integration test

**Comment by llbartekll** [comment]
- [ ] EIP-1271 Signature Verifier
- [ ] App EIP-191 response handler (should be extracted from AppRespondSubscriber)
- [ ] App EIP-1271 response handler
- [ ] Refactor message signer to support CacaoSignature eip191 and eip1271
