### ISSUE TITLE
WalletConnectModal milestone v1

### ISSUE THREAD

**Issue by radeknovis** [WalletConnect/WalletConnectSwiftV2#832]
### WalletConnectModal Swift Milestone 1

Mobile native version of WalletConnectModal available in Swift SDK

### SDK 
```[tasklist]
- [x] Show QR Code
- [x] Customizable cloud PROJECT_ID
- [x] Connect with Wallet
- [x] Support Navigation Component via SwiftUI
- [x] Support Navigation Component via UIKit
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/903
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/833
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/834
- [ ] https://github.com/WalletConnect/WalletConnectSwiftV2/issues/871
```

### Web3Modal

- Review Web3Modal Native: [project brief](https://docs.google.com/document/d/1H0izti1L9dFDTzWcBDqskYB5qO5SFFB0kq9n-wKfGbs/edit)

**Comment by cao13646** [comment]
IOS 14，WalletConnectModalSheetController dismiss， leaving a layer of gray view
